/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Juan
 */
public class VistaEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form MenuEmpleados
     */
    public VistaEmpleado() {
        initComponents();
    }

    public JLabel getVal_horario() {
        return Val_horario;
    }

    public void setVal_horario(JLabel Val_horario) {
        this.Val_horario = Val_horario;
    }

    public JButton getBtn_Guardar() {
        return btn_Guardar;
    }

    public void setBtn_Guardar(JButton btn_Guardar) {
        this.btn_Guardar = btn_Guardar;
    }

    public JButton getBtn_crear() {
        return btn_crear;
    }

    public void setBtn_crear(JButton btn_crear) {
        this.btn_crear = btn_crear;
    }

    public JButton getBtn_eliminar() {
        return btn_eliminar;
    }

    public void setBtn_eliminar(JButton btn_eliminar) {
        this.btn_eliminar = btn_eliminar;
    }

    public JButton getBtn_modificar() {
        return btn_modificar;
    }

    public void setBtn_modificar(JButton btn_modificar) {
        this.btn_modificar = btn_modificar;
    }

    public JComboBox<String> getCb_horario() {
        return cb_horario;
    }

    public void setCb_horario(JComboBox<String> cb_horario) {
        this.cb_horario = cb_horario;
    }

    public JDateChooser getDc_FechaContrato() {
        return dc_FechaContrato;
    }

    public void setDc_FechaContrato(JDateChooser dc_FechaContrato) {
        this.dc_FechaContrato = dc_FechaContrato;
    }

    public JDialog getDlg_CrearEdit() {
        return dlg_CrearEdit;
    }

    public void setDlg_CrearEdit(JDialog dlg_CrearEdit) {
        this.dlg_CrearEdit = dlg_CrearEdit;
    }

    public JSpinner getSp_salario() {
        return sp_salario;
    }

    public void setSp_salario(JSpinner sp_salario) {
        this.sp_salario = sp_salario;
    }

    public JTable getTbl_empleados() {
        return tbl_empleados;
    }

    public void setTbl_empleados(JTable tbl_empleados) {
        this.tbl_empleados = tbl_empleados;
    }

    public JTextField getTxt_apellidos() {
        return txt_apellidos;
    }

    public void setTxt_apellidos(JTextField txt_apellidos) {
        this.txt_apellidos = txt_apellidos;
    }

    public JTextField getTxt_busqueda() {
        return txt_busqueda;
    }

    public void setTxt_busqueda(JTextField txt_busqueda) {
        this.txt_busqueda = txt_busqueda;
    }

    public JTextField getTxt_cedula() {
        return txt_cedula;
    }

    public void setTxt_cedula(JTextField txt_cedula) {
        this.txt_cedula = txt_cedula;
    }

    public JTextField getTxt_discapacidad() {
        return txt_discapacidad;
    }

    public void setTxt_discapacidad(JTextField txt_discapacidad) {
        this.txt_discapacidad = txt_discapacidad;
    }

    public JTextField getTxt_nombres() {
        return txt_nombres;
    }

    public void setTxt_nombres(JTextField txt_nombres) {
        this.txt_nombres = txt_nombres;
    }

    public JLabel getVal_apellido() {
        return val_apellido;
    }

    public void setVal_apellido(JLabel val_apellido) {
        this.val_apellido = val_apellido;
    }

    public JLabel getVal_cedula() {
        return val_cedula;
    }

    public void setVal_cedula(JLabel val_cedula) {
        this.val_cedula = val_cedula;
    }

    public JLabel getVal_discapacidad() {
        return val_discapacidad;
    }

    public void setVal_discapacidad(JLabel val_discapacidad) {
        this.val_discapacidad = val_discapacidad;
    }

    public JLabel getVal_nombres() {
        return val_nombres;
    }

    public void setVal_nombres(JLabel val_nombres) {
        this.val_nombres = val_nombres;
    }

    public JLabel getVal_salario() {
        return val_salario;
    }

    public void setVal_salario(JLabel val_salario) {
        this.val_salario = val_salario;
    }

    public JLabel getVel_fecha() {
        return vel_fecha;
    }

    public void setVel_fecha(JLabel vel_fecha) {
        this.vel_fecha = vel_fecha;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg_CrearEdit = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        btn_Guardar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_discapacidad = new javax.swing.JTextField();
        sp_salario = new javax.swing.JSpinner();
        dc_FechaContrato = new com.toedter.calendar.JDateChooser();
        cb_horario = new javax.swing.JComboBox<>();
        Val_horario = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        val_cedula = new javax.swing.JLabel();
        val_nombres = new javax.swing.JLabel();
        val_apellido = new javax.swing.JLabel();
        vel_fecha = new javax.swing.JLabel();
        val_salario = new javax.swing.JLabel();
        val_discapacidad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_empleados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_crear = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_busqueda = new javax.swing.JTextField();

        btn_Guardar.setText("Guardar ");
        jPanel4.add(btn_Guardar);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Empleado")));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Cedula");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 32, -1, -1));

        jLabel3.setText("Nombres");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setText("Apellidos");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 20));

        jLabel5.setText("Fecha de contrato");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel6.setText("Salario");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel7.setText("Discapacidad");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel8.setText("Horario");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel6.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 170, -1));
        jPanel6.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, -1));
        jPanel6.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, -1));
        jPanel6.add(txt_discapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, -1));

        sp_salario.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));
        jPanel6.add(sp_salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 110, -1));
        jPanel6.add(dc_FechaContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, -1));

        cb_horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione un Horario-", "Diurno", "Nocturno", "Mixto" }));
        jPanel6.add(cb_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 170, -1));

        Val_horario.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Val_horario.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(Val_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 160, 20));
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 130, -1));

        val_cedula.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        val_cedula.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(val_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 160, 20));

        val_nombres.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        val_nombres.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(val_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 160, 20));

        val_apellido.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        val_apellido.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(val_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 160, 20));

        vel_fecha.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        vel_fecha.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(vel_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, 20));

        val_salario.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        val_salario.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(val_salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 160, 20));

        val_discapacidad.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        val_discapacidad.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(val_discapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 160, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlg_CrearEditLayout = new javax.swing.GroupLayout(dlg_CrearEdit.getContentPane());
        dlg_CrearEdit.getContentPane().setLayout(dlg_CrearEditLayout);
        dlg_CrearEditLayout.setHorizontalGroup(
            dlg_CrearEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlg_CrearEditLayout.setVerticalGroup(
            dlg_CrearEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_CrearEditLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("imprimir 1");
        jPanel1.add(jButton4);

        jButton5.setText("imprimir 2");
        jPanel1.add(jButton5);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tbl_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CEDULA", "NOMBRES", "APELLIDOS", "FECHA CONTRATO", "SALARIO", "DISCAPACIDAD", "HORARIO"
            }
        ));
        jScrollPane1.setViewportView(tbl_empleados);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btn_crear.setText("CREAR");

        btn_modificar.setText("MODIFICAR");

        btn_eliminar.setText("ELIMINAR");

        jLabel1.setText("BUSCADOR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btn_crear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminar)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crear)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Val_horario;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cb_horario;
    private com.toedter.calendar.JDateChooser dc_FechaContrato;
    private javax.swing.JDialog dlg_CrearEdit;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sp_salario;
    private javax.swing.JTable tbl_empleados;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_busqueda;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_discapacidad;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JLabel val_apellido;
    private javax.swing.JLabel val_cedula;
    private javax.swing.JLabel val_discapacidad;
    private javax.swing.JLabel val_nombres;
    private javax.swing.JLabel val_salario;
    private javax.swing.JLabel vel_fecha;
    // End of variables declaration//GEN-END:variables
}
